### ISSUE TITLE
A problem.

### ISSUE THREAD

**Issue by mianzhang** [declare-lab/dialogue-understanding#1]
Hi, I encounter an error when executing the codes using the command "python train.py --dataset iemocap --classify emotion --cls-model lstm --residual".
![image](https://user-images.githubusercontent.com/31158330/95536614-fbd06500-0a1d-11eb-9584-56efa6bad3ec.png)
Is there something wrong with the codes?

**Comment by mianzhang** [comment]
In glove-end-to-end.

**Comment by deepanwayx** [comment]
Can you pull the latest branch and try again?

**Comment by mianzhang** [comment]
Fixed, thanks a lot.
