### ISSUE TITLE
CNN extractor Prob.

### ISSUE THREAD

**Issue by Columbine21** [declare-lab/dialogue-understanding#2]
In your paper, the convoluted features are then max-pooled **with a window size of 2**(consists with the annotations). But in your code the max-pooled window size is the **second dimension length of the Conv1d output**. Is that actually what you want?

https://github.com/declare-lab/dialogue-understanding/blob/4fef597c423bdb2dc1642030c80763ee45c826ff/glove-end-to-end/model.py#L294

**Comment by Columbine21** [comment]
https://github.com/declare-lab/dialogue-understanding/blob/4fef597c423bdb2dc1642030c80763ee45c826ff/glove-end-to-end/model.py#L296
I don't think the dimension of "concated" tensor is in the shape of (num_utt * batch, embedding_dim//2).

**Comment by deepanwayx** [comment]
Thanks for pointing it out. Yes, you are correct. The max-pooling is performed across the time dimension following Kim's original text CNN model. We have already revised the paper in arxiv.

The shape of the "concated" tensor is (num_utt * batch, len(kernel_sizes) * filters)

**Comment by Columbine21** [comment]
Many thanks. Don't forget to change your paper link in your Readme page. 
Wish you good luck
