### ISSUE TITLE
 I have a question during the training process.

### ISSUE THREAD

**Issue by so-hyeun** [declare-lab/dialogue-understanding#5]
First of all, thank you for doing interesting research. 
I have a question in the process of training the roberta-end-to-end model (DialogueRNN).

1) How can i use multi-gpu?

2) Is it possible to use the latest transformers version (4.3.2)?

**Comment by deepanwayx** [comment]
1. The functionality to use multi-gpu is not provided here. But it should not be difficult to add it by following the official pytorch example: https://pytorch.org/tutorials/beginner/former_torchies/parallelism_tutorial.html

2. You might have to make a couple of very minor changes to use the transformers 4.3.2 version. Line [366-368](https://github.com/declare-lab/dialogue-understanding/blob/master/roberta-end-to-end/model.py#L366) may have to changed to make sure that the `features` variable contains the final layer vectors corresponding to the `<CLS>` token for the utterances.

**Comment by so-hyeun** [comment]
Thanks for the answer. 
One more question, in the case of RoBERTa+DialogueRNN, where is the trained model stored?

**Comment by deepanwayx** [comment]
The trained models are not stored by default. We run each experiment multiple times and the space to store them all of them quickly turns out to be huge.

You could use the usual `torch.save` to save the models in your preferred directory.

**Comment by so-hyeun** [comment]
Thanks for the kind and quick reply.
