### ISSUE TITLE
Performance for DailyDialog

### ISSUE THREAD

**Issue by so-hyeun** [declare-lab/dialogue-understanding#6]
Hi. I have a question for reproducing performance for dailydialog.

![performance_dailydialog](https://user-images.githubusercontent.com/55587907/109443544-2dee6c00-7a7e-11eb-87b7-2f49cdaef6d0.PNG)

1) In the photo, @Best Valid F1 values ​​are Test F1 values ​​when validation F1 is the highest?

2) I train the model with batch size =1 due to the computing power problem,. 
Can this be the cause of the difference between the performance of the paper (59.50) and my performance (57.5)?

**Comment by deepanwayx** [comment]
1. Yes, the scores are test F1 values at highest validation F1 values.

2. Yes exactly. If you have a look at the Section 5.1 and Figure 12 in our paper, you would notice that the performance is heavily dependent on the batch size. In DailyDialog, smaller batch size results in poorer performance. I would also suggest that you run each experiment several times and take the average of the results to obtain results closer to ours.

**Comment by so-hyeun** [comment]
Thanks for the kind and quick reply.
