### ISSUE TITLE
the Label Shift part is quite confusing to me and the code does not contain this part

### ISSUE THREAD

**Issue by yucc-leon** [declare-lab/dialogue-understanding#7]
Hi, I read about the _An Empirical Study_ paper and don't understand what you did when during the Intra- or Inter- Speaker Shift experiment. Did you select the specific samples only with shifts happen or use some other techniques? 
I want to see the detail in the code but apparently they are not published. Would you please kindly explain a little?

**Comment by soujanyaporia** [comment]
Yes, I think @deepanwayx selected the utterances where shifted happened and specifically analyzed the model's performance for those subsets. Hope this helps.

**Comment by yucc-leon** [comment]
> Yes, I think @deepanwayx selected the utterances where shifted happened and specifically analyzed the model's performance for those subsets. Hope this helps.

I see, thanks a lot.
